name: Test & Lint [Web]

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  test:
    name: Test & Lint [Web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
          cache-dependency-path: web/yarn.lock
      - run: cd web && yarn install
      - run: cd web && yarn compile
      - run: cd web && yarn lint
